### ISSUE TITLE
CPU - Memory (Byte Addressable)

### ISSUE THREAD

**Issue by Dishoungh** [Dishoungh/cpu#1]
I'm having trouble implementing some sizeable byte addressable memory for my Logisim project. For context for those who are wanting to help me, I have journaled everything I've done so far in the [README on the front page](https://github.com/Dishoungh/cpu). I need help differentiating between storing/loading a byte, a halfword, and a full word. This is what I have so far.

![image](https://github.com/Dishoungh/cpu/assets/47036723/70f80db0-39b0-41a2-9dad-a4cacc5f007c)

I know I'm missing something. I just need to figure it out and document it.

**Comment by MahirAbbas** [comment]
is this memory a cache, RAM or storage?

**Comment by Dishoungh** [comment]
@MahirAbbas This is just RAM. I'm not implementing cache yet. Also, the details are in the README. Particularly, the [Memory implementation section](https://github.com/Dishoungh/cpu/blob/master/README.md#memory-program-and-data)

**Comment by MahirAbbas** [comment]
forgive me if I'm being naive, but can't you input a 2 bit signal that indicates the size (word/ half word etc.) that then creates a read/write mask? Is that possible in Logism?

**Comment by Dishoungh** [comment]
@MahirAbbas I have updated the README: https://github.com/Dishoungh/cpu?tab=readme-ov-file#memory-program-and-data

You mean something like that? I feel like I'm still doing something wrong with the memory addressing but I think I'm getting close.

**Comment by Dishoungh** [comment]
@MahirAbbas I think I got it working though I don't think it's perfect and a very realistic model, but I think it's good enough for now considering I don't think it's possible to access multiple addresses at the same time...at least right now with my idealized model. I'm still trying to figure out how I can have this work for both data and accessing new instructions especially since I'm trying to target a Von Neumann type architecture.

Maybe have one cycle fetch the next instruction and have one cycle fetch data if needed? Maybe?

Sorry, if I'm just rambling. I'm trying to fill in the holes in my lack knowledge of this stuff.

**Comment by MahirAbbas** [comment]
You're creating a RAM. You can't differentiate between instructions and data. You might be getting data/instruction caches mixed up.

**Comment by Dishoungh** [comment]
@MahirAbbas 

> You're creating a RAM. You can't differentiate between instructions and data.

Right. This is Von Neumann.

> You might be getting data/instruction caches mixed up.

Perhaps. Because the way they taught me in school, they didn't differentiate between data/program caches and the main system memory (RAM). And that always confused me. Right now, I was initially thinking to implement main system memory first and then implement caches later. But if you think it would be easier to do the opposite, that's fine.

> If you are using the RAM for the CPU memory, I would suggest following the textbook and creating 2 of them. One for data, and another for instructions.

But isn't that Harvard and not Von Neumann though or am I still misunderstanding?

**Comment by Dishoungh** [comment]
@MahirAbbas Btw, do you mind if I credit you in my "Special Thanks" list? I'm putting people who help me with my project there.

**Comment by MahirAbbas** [comment]
let's carry this conversation on in discord

**Comment by Dishoungh** [comment]
I'm closing this issue. I've been referenced to likely a helpful book that can help guide my design. I need to rethink my strategy and restructure my documentation.
